### ISSUE TITLE
☂️ Functionality for v0.1

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/scip-clang#2]
## Language support

This is a rough checklist of language features for which we should support Go to Def/Find Refs in a v0.1 release of scip-clang.

### Very important

- [x] Local variables (https://github.com/sourcegraph/scip-clang/pull/113)
- [x] Function parameters (https://github.com/sourcegraph/scip-clang/pull/113)
- [x] Data members (https://github.com/sourcegraph/scip-clang/pull/131)
- [x] Ordinary named functions and methods (https://github.com/sourcegraph/scip-clang/pull/122)
- [x] Operators (https://github.com/sourcegraph/scip-clang/pull/122)
- [x] Explicitly written constructors (approximate: https://github.com/sourcegraph/scip-clang/pull/163)
- [x] Types (enums, classes, structs, unions) (https://github.com/sourcegraph/scip-clang/pull/98, https://github.com/sourcegraph/scip-clang/pull/80, https://github.com/sourcegraph/scip-clang/pull/116)
- [x] Type aliases (https://github.com/sourcegraph/scip-clang/pull/135)
- [x] Forward declarations (https://github.com/sourcegraph/scip-clang/pull/148)
- [ ] Hover docs: type information
- [x] Hover docs: doc comments
- [x] Adoption docs

### Important

- [x] Namespaces (https://github.com/sourcegraph/scip-clang/pull/76)
- [x] Namespace aliases
- [x] Template parameters (https://github.com/sourcegraph/scip-clang/pull/133)
- [x] Macro names (https://github.com/sourcegraph/scip-clang/pull/61, https://github.com/sourcegraph/scip-clang/pull/78)
- [x] Global variables (https://github.com/sourcegraph/scip-clang/pull/131)
- [x] `#include` pragmas (https://github.com/sourcegraph/scip-clang/issues/107, https://github.com/sourcegraph/scip-clang/pull/166)
- [x] ~Full and partial template specializations~ Moved out of v0.1 to https://github.com/sourcegraph/scip-clang/issues/278

### Low importance (for MVP)

- Synthesized constructors

- Navigation in macro body

## Build system support

- [x] Indexing in parallel locally using `compile_commands.json` https://github.com/sourcegraph/scip-clang/pull/8
- [x] Graceful handling for hangs/slow indexing - #20
- [ ] Graceful handling for unknown compiler flags
- [x] GCC-based builds https://github.com/sourcegraph/scip-clang/issues/177 (https://github.com/sourcegraph/scip-clang/pull/178)
- [x] Graceful handling for compilation errors

**Comment by varungandhi-src** [comment]
Closing this since v0.1 is released. The type information problem is tracked in #327
